config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, :controllers => { omniauth_callbacks: 'omniauth_callbacks', registrations: 'registrations',  }
  post '/signup' => 'splash#signup', as: :splash_signup
  get '/splash' => 'splash#index'
  get '/splash/get_timesheet_atom' => 'splash#get_timesheet_atom'
  put '/splash/post_timesheet' => 'splash#post_timesheet'
  root 'splash#index'
  get 'reports' => 'reports#index'
  get '/setup' => 'setup#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/splash_controller.rb
class SplashController < ApplicationController
  skip_before_action :authenticate
  before_action :authenticate_user!

  skip_before_action :verify_authenticity_token

  def get_timesheet_atom
    @category = Category.find params[:modal_category_id]
    @task = Task.find params[:modal_task_id]
    render partial: 'splash/timesheet_atom', locals: {category: @category, task: @task}
  end

  def post_timesheet
    params[:mins].each {|key, value|
      begin
        task_id, category_id, timesheet_date = key.split('$')
        puts "timesheet_date #{timesheet_date}"
        timesheet_date = Date.parse(timesheet_date)
        mins = value
        time_track = current_user.time_trackers.find_or_create_by(task_id: task_id, category_id: category_id, billable_date: timesheet_date)
        time_track.update(time_consumed: mins.to_i)
      rescue => e
        next
      end
    }

    render :text => 'Timesheet submitted successfully!'
  end

  def index
    @current_week_projects = current_user.current_week_projects
  end

  def new

  end

  def signup
    if ENV['MAILCHIMP_SPLASH_SIGNUP_LIST_ID'].blank? or ENV['MAILCHIMP_API_KEY'].blank?

      @message = "The MAILCHIMP_API_KEY and MAILCHIMP_SPLASH_SIGNUP_LIST_ID environment variables need to be set for mailing list signup to work! If you don't want this feature, you can just remove the mailing list signup feature from app/views/splash/index.html.haml"

    else
      begin

        gb = Gibbon::Request.new(api_key: ENV['MAILCHIMP_API_KEY'])

        gb.lists(ENV['MAILCHIMP_SPLASH_SIGNUP_LIST_ID']).members.create(
            body: {
                email_address: params[:signup_email],
                status: "pending"
            }
        )

        @message = 'Thanks for signing up!'

      rescue StandardError => e
        @error = true

        if e.message =~ /is already subscribed to the list/
          @message = "You're already signed up to receive updates. Thanks for your enthusiasm!"
        else
          @message = "Oops! Looks like we ran into an error. How embarrassing. Please try again later!"
        end

      end
    end
  end


  private

  def gem_available?(name)
    Gem::Specification.find_by_name(name)
  rescue Gem::LoadError
    false
  rescue
    Gem.available?(name)
  end

end

app/views/splash/_category_picker.html.haml
#myModal.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "exampleModalLabel", :role => "dialog", :tabindex => "-1"}
  .modal-dialog{:role => "document"}
    .modal-content
      .modal-header
        %h5#exampleModalLabel.modal-title Pick Category
        %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
          %span{"aria-hidden" => "true"} ×
      .modal-body.modal_message
      - # Project Tasks slection
      -  grouped_task_options= @current_week_projects.map do |project|
        - [project.name, project.tasks.collect{|t| [t.name, t.id]}]
      - grouped_category_options = Category.parent_nodes.map do |parent|
        - [parent.name, parent.children.collect{|c| [c.name, c.id]}]

      .modal-body
        = select_tag "modal_category_id", grouped_options_for_select(grouped_category_options), include_blank: true, class: "form-control"

      - # Category selection
      .modal-body
        = select_tag "modal_task_id", grouped_options_for_select(grouped_task_options), include_blank: true, class: "form-control"
      .modal-footer
        %button.btn.btn-secondary{"data-dismiss" => "modal", :type => "button"} Close
        %button.btn.btn-primary#select_category_button{:type => "button"} Save changes

app/views/splash/_environment_checks.html.haml
%ul.list-group

  - if ENV['AWS_ACCESS_KEY_ID'].blank? or ENV['AWS_SECRET_ACCESS_KEY'].blank?
    %li.list-group-item.list-group-item-danger
      %h4 AWS
      You haven't set up your AWS account in this environment! Set the <code>AWS_ACCESS_KEY_ID</code> and <code>AWS_SECRET_ACCESS_KEY</code> environment variables to configure AWS. You should have the client sign up and follow the instructions below.
  - else
    %li.list-group-item.list-group-item-success
      %h4 AWS
      Your AWS account is configured for this environment!



  - if ENV['GOOGLE_ANALYTICS_SITE_ID'].blank?
    %li.list-group-item.list-group-item-danger
      %h4 Google Analytics
      You haven't set up a Google Analytics account in this environment! Set the <code>GOOGLE_ANALYTICS_SITE_ID</code> environment variables to configure Google Analytics. You should ask the client to <a href="http://google.com/analytics/" target="_blank">set up a Google Analytics account</a>.
  - else
    %li.list-group-item.list-group-item-success
      %h4 Google Analytics
      Your Google Analytics account is configured for this environment!



  - unless @tracker_gems.values.any?
    %li.list-group-item.list-group-item-danger
      %h4 Exception Tracking
      You haven't set up an exception tracker! May I recommend <a href="https://addons.heroku.com/honeybadger" target="_blank">Honeybadger</a>?
  - else
    %li.list-group-item.list-group-item-success
      %h4 Exception Tracking
      Found exception tracker gems(s):
      = @tracker_gems.select{|k,v| v}.keys.join(', ')



  - if ENV['MAILCHIMP_API_KEY'].blank?
    %li.list-group-item.list-group-item-danger
      %h4 Mailchimp
      <p>You haven't set up a Mailchimp account in this environment! Have the client create an account at <a href="http://mailchimp.com" target="_blank">mailchimp.com</a> and set the <code>MAILCHIMP_API_KEY</code> environment variables to configure Mailchimp.</p>
      <p>Once a Mailchimp account is configured, you'll need to create a list through the web interface and set the <code>MAILCHIMP_SPLASH_SIGNUP_LIST_ID</code> environment variable to the list id (ten-digit hex id visible in the List name &amp; defaults tab).</p>
  - else
    %li.list-group-item.list-group-item-success
      %h4 Mailchimp
      Your Mailchimp account is configured for this environment!

app/views/splash/_lightimage.html.haml
%section.lightimage
  .container
    .row
      .inner-column
        %h1 Big Fat Title

        %p.info Great descriptive content
        = link_to "Call to Action", root_url, class: "btn btn-primary btn-lg"

app/views/splash/_plot_footer.html.haml
%tr
  %td.name
    %button{class:"btn btn-primary", data: {toggle:"modal", target:"#myModal"}, :tabindex => "2", :type => "button"} New Row
    %button#submit_timesheet{class: 'btn btn-success', :tabindex => "1", :type => "button"} Save
    %span.last-saved.do-not-print Last saved at 12:43pm
  %td.day.test-not-today.test-day-total-1 7:00
  %td.day.test-not-today.test-day-total-2 6:30
  %td.day.today.test-day-total-3 0
  %td.day.test-not-today.test-day-total-4 8:00
  %td.day.test-not-today.test-day-total-5 0
  %td.day.test-not-today.test-day-total-6 0
  %td.day.test-not-today.test-day-total-0 0
  %td.total 21:30
  %td.delete

app/views/splash/_plot_header.html.haml
- current_date = week_start_date = Date.today.at_beginning_of_week(start_day = :monday)
- week_end_date = Date.today.at_end_of_week(start_day = :monday)

%tr
  %td.name
  - while(current_date <= week_end_date) do
    %td.day
      %a{:href => "#", :tabindex => "1", :title => "Monday", title: current_date.strftime('%m/%d/%Y')}
        =current_date.strftime("%A")[0]
        %span=current_date.strftime('%d %b')
    - current_date += 1
  %td.total  
  %td.delete

app/views/splash/_time_tacker.html.haml
.container
  %section.primary#about
    = form_tag(splash_post_timesheet_path, method: :put, id: 'timesheet_form') do
      %table.table-striped.week-view-table
        %thead
          = render partial: 'splash/plot_header'
        %tbody#time_sheet_container
        %tfoot
          = render partial:  'plot_footer'
= render partial: 'splash/category_picker'

app/views/splash/_timesheet_atom.html.haml
- current_date = week_start_date = Date.today.at_beginning_of_week(start_day = :monday)
- week_end_date = Date.today.at_end_of_week(start_day = :monday)

%tr.week-view-entry{:style => "display: table-row;"}
  %td.name
    .project-client
      %span.project= @task.project.name
      %span.client="(#{@task.name})"
    .task=@category.name
  - while(current_date <= week_end_date) do
    %td.day.test-not-today
      %input.docker-input.js-compound-entry{:tabindex => "1", :type => "text", :value => "", name: "mins[#{@task.id}$#{@category.id}$#{current_date.strftime('%d-%m-%Y')}]"}/
    - current_date += 1
  %td.total 3:00
  %td.delete.js-end-of-week-row.test-zero-hours
    %button.hui-button.hui-button-tiny.button-icon-only.week-row-delete.js-remove-row{:tabindex => "1", :title => "Delete Row", :type => "button"}
      %i{"data-icon" => "x"}
    .popover.popover-confirm.is-down-right.popover-week-delete{"aria-hidden" => "true"}
      %p Remove entries from timesheet?
      .buttons
        %button.hui-button.hui-button-small.hui-button-important.js-confirm-delete-entry.js-bubble{:type => "button"} Delete
        %button.hui-button.hui-button-small.hui-button-cancel.js-cancel-delete-entry.js-bubble{:type => "button"} Cancel

app/views/splash/index.html.haml
= render partial: 'splash/time_tacker'


%section.contact#contact
  .container
    .row
      .inner-column
        %h1 Please raise complaint, if you are not able to fill the timesheet.
        = form_tag splash_signup_path, role: :form, remote: true do
          .form-group
            .input-group
              = text_field_tag :signup_email, "", class: "form-control", placeholder: 'E-Mail', type: "email"
              %span.input-group-btn
                = submit_tag 'Sign up', class: 'btn btn-primary'
          %small#signup-message

app/views/splash/signup.js.erb
<% if @error %>
  $('#signup').addClass('has-error');
<% else %>
  $('#signup').removeClass('has-error');
  $('#signup_email').val('');
<% end %>

$('#signup-message').text("<%= j @message.html_safe %>").hide().slideDown('fast');